#!/bin/sh

DOTFILES_DIR=$(cd $(dirname $0);pwd)
CONFIG_HOME=$HOME/.config
CACHE_HOME=$HOME/.cache

# git
[ ! -L ~/.gitconfig ] && ln -s $DOTFILES_DIR/.gitconfig ~/.gitconfig

# zsh/zprezto/zplug
[ ! -L ~/.zplug ]     && ln -s $DOTFILES_DIR/.zplug/ ~/.zplug
[ ! -L ~/.zshenv ]    && ln -s $DOTFILES_DIR/.zshenv ~/.zshenv
[ ! -L ~/.zshrc ]     && ln -s $DOTFILES_DIR/.zshrc ~/.zshrc

# tmux
[ ! -L ~/.tmux.conf ] && ln -s $DOTFILES_DIR/.tmux.conf ~/.tmux.conf
[ ! -e ~/.tmux/plugins ] && mkdir -p ~/.tmux/plugins
[ ! -L ~/.tmux/plugins/tpm ] && ln -s $DOTFILES_DIR/tpm ~/.tmux/plugins/tpm

# vim
[ ! -L ~/.vimrc ]     && ln -s $DOTFILES_DIR/.vimrc ~/.vimrc
sh $DOTFILES_DIR/dein.vim/bin/installer.sh $CACHE_HOME/dein > /dev/null

# fzf
$DOTFILES_DIR/fzf/install --no-key-bindings --completion --no-update-rc --no-bash --no-fish > /dev/null
