#!/bin/sh

create_symlink() {
  if [ ! -L "$2" ]; then
    ln -s "$1" "$2"
  fi
}

create_directory() {
  if [ ! -e "$1" ]; then
    mkdir -p "$1"
  fi
}

DOTFILES_DIR=$(cd "$(dirname "$0")";pwd)
CONFIG_HOME=$HOME/.config
CACHE_HOME=$HOME/.cache

# zsh/zprezto/zplug
create_symlink "$DOTFILES_DIR/.zplug" "$HOME/.zplug"
create_symlink "$DOTFILES_DIR/.zshrc" "$HOME/.zshrc"

# fzf
"$DOTFILES_DIR/fzf/install" --no-key-bindings --completion --no-update-rc --no-bash --no-fish > /dev/null
